language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov
  - pip install codeclimate-test-reporter

script: 
  - pytest --cov-report term-missing --cov=app 

after-success:
  - coveralls 
  - codeclimate-test-reporter
